apiVersion: apps/v1
kind: Deployment
metadata:
  name: "go-test"
  labels:
    app: "go-test"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "go-test"
  template:
    metadata:
      labels:
        app: "go-test"
    spec:
      containers:
      - name: "go-agent"
        image: golang:alpine
        env:
          - name: NODE_IP
            valueFrom: { fieldRef: { fieldPath: status.hostIP } }
          - name: NODE_NAME
            valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
          - name: POD_NAME
            valueFrom: { fieldRef: { fieldPath: metadata.name } }

