containerRuntime: "docker" #docker, containerd, crio 중 선택 kubectl get nodes -o wide 명령어 CONTAINER-RUNTIME 의 값 참고
whatap:
  license: ""
  host: ""
  port: "6600"
deployment:
  containers:
    controlPlaneHelper:
      enabled: true
      debug: true