whatap:
  license: "x423h2197u810-x1jh0prkj2ofme-z2v3cc6u6r6fjk"
  host: "15.165.146.117"
  port: "6600"
collect_custom_resources: false
hostNetworkEnabled: false
# whatapResourceAlreadyExist: false
# istioEnabled default
#istioEnabled: false

# k8sOldVersion default
#k8sOldVersion: true

# collect_apiserver_metric_by_leader default
collect_apiserver_metric_by_leader: false

addon:
  npm:
    enabled: false
  gpu:
    enabled: false
    image: nvcr.io/nvidia/k8s/dcgm-exporter:2.1.8-2.4.0-rc.3-ubuntu18.04
  apiserver_monitoring:
    enabled: false # Set to true to use apiserver_monitoring_dashboard(default false)
    client_tls_verify: true # Set to false to skip insecure-tls-verify(default true)
  etcd_monitoring:
    enabled: false # Set to true to use apiserver_monitoring_dashboard(default false)
    # Set path to use customized path
    # minikube: /var/lib/minikube/certs/etcd
    etcd_ca_cert_path: /etc/kubernetes/pki/etcd/ca.crt
    etcd_client_cert_path: /etc/kubernetes/pki/etcd/server.crt
    etcd_client_key_path: /etc/kubernetes/pki/etcd/server.key
imagePullSecret:
  name: #registryKey
containerRuntime: "docker" # Options: "docker", "containerd", "crio"
daemonSet:
  name: whatap-node-agent
  label: whatap-node-agent
  initContainers:
    nodeDebugger:
      enabled: true  # Set to false to disable the whatap-node-debug initContainer
      name: whatap-node-debug
      image: "whatap/kube_mon"
  containers:
    nodeHelper:
      name: whatap-node-helper
      image: "whatap/kube_mon"
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "350Mi"
        cpu: "200m"
      envs:
        collect_nfs_disk_enabled: true
        collect_kube_node_process_metric_enabled: false
        collect_kube_node_process_metric_target_list: "kubelet,containerd,dockerd,crio,coredns,kube-proxy,aws-k8s-agent,kube-apiserver,etcd,kube-controller,kube-scheduler"
        debug: false
    nodeAgent:
      name: whatap-node-agent
      image: "whatap/kube_mon"
      requests:
        memory: "300Mi"
        cpu: "100m"
      limits:
        memory: "350Mi"
        cpu: "200m"
      envs:
        collect_kube_node_process_metric_enabled: false
        debug: false
deployment:
  name: whatap-master-agent
  label: whatap-master-agent
  replicas: 1
  containers:
    controlPlaneHelper:
      enabled: true  # Set to false to disable the whatap-control-plane-helper container
      debug: false
      name: whatap-control-plane-helper
      image: whatap/kube_mon
      port: 9496
      resources:
        requests:
          memory: "500Mi"
          cpu: "500m"
        limits:
          memory: "500Mi"
          cpu: "500m"
    masterAgent:
      name: whatap-master-agent
      image: "whatap/kube_mon"
      port: 6600
      resources:
        requests:
          memory: "300Mi"
          cpu: "100m"
        limits:
          memory: "350Mi"
          cpu: "200m"
      envs:
        debug: false
clusterrole:
  extraResources:
    - "samplecrds"