{{- $managedResources := .Values.managedResources | default dict -}}
{{- if or (not (hasKey $managedResources "masterService")) (get $managedResources "masterService") }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    run: whatap-master-agent
  name: whatap-master-agent
spec:
  clusterIP: None
  ports:
    - port: 6600
      protocol: TCP
      name: tcp-whatap-master-agent
    - port: 6800
      protocol: TCP
      name: tcp-whatap-confbase
  selector:
    name: whatap-master-agent
{{- end }}
