{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" "whatap") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: whatap
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]
  - nonResourceURLs: [ "/metrics" ]
    verbs: [ "*" ]
{{- end }}