apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatap-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatap-operator
  template:
    metadata:
      labels:
        app: whatap-operator
    spec:
      serviceAccountName: whatap-operator
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          ports:
            - containerPort: 9443
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
