apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatap-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "whatap-operator"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "whatap-operator"
    spec:
      {{- if .Values.imagePullSecret.name }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
      {{- end }}
      serviceAccountName: whatap-operator
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          ports:
            - containerPort: 9443
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: WHATAP_DEFAULT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WHATAP_LICENSE
              valueFrom:
                secretKeyRef:
                  name: whatap-credentials
                  key: WHATAP_LICENSE
            - name: WHATAP_HOST
              valueFrom:
                secretKeyRef:
                  name: whatap-credentials
                  key: WHATAP_HOST
            - name: WHATAP_PORT
              valueFrom:
                secretKeyRef:
                  name: whatap-credentials
                  key: WHATAP_PORT
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: false
      volumes:
        - name: webhook-certs
          emptyDir: {}
