{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" "whatap-operator") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: whatap-operator
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups: ["monitoring.whatap.com"]
    resources: ["whatapagents", "whatapagents/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "update", "patch","delete"]
{{- end }}