{{- $managedResources := .Values.managedResources | default dict -}}
{{- if or (not (hasKey $managedResources "serviceAccounts")) (get $managedResources "serviceAccounts") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whatap-operator
  namespace: {{ .Release.Namespace }}
{{- end }}
