{{- if not (lookup "v1" "ServiceAccount" .Release.Namespace "whatap-operator") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whatap-operator
  namespace: {{ .Release.Namespace }}
{{- end }}