{{- $cred := .Values.credentials | default dict -}}
{{- if $cred.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: whatap-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  WHATAP_LICENSE: {{ $cred.license | default "" | b64enc }}
  WHATAP_HOST: {{ $cred.host | default "" | b64enc }}
  WHATAP_PORT: {{ $cred.port | default 6600 | toString | b64enc }}
{{- end }}
