{{- if not  .Values.whatapResourceAlreadyExist}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: whatap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: whatap
subjects:
  - kind: ServiceAccount
    name: whatap
    {{ if not .Values.namespaceOverrideEnabled }}
    namespace: "whatap-monitoring"
    {{ else}}
    namespace: {{ .Release.Namespace }}
    {{ end }}
{{- end }}