{{- if not  .Values.whatapResourceAlreadyExist}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: whatap
  {{ if not .Values.namespaceOverrideEnabled }}
  namespace: "whatap-monitoring"
  {{ else}}
  namespace: {{ .Release.Namespace }}
  {{ end }}
rules:
  - apiGroups: ["*"]
    {{ if not .Values.clusterrole.rules.resources }}
    resources: ["namespaces", "pods", "pods/log", "configmaps","services", "endpoints","daemonsets","ingresses","deployments","nodes","persistentvolumes","persistentvolumeclaims", "events", "replicasets", "roles", "rolebindings", "clusterroles", "clusterrolebindings", "jobs", "cronjobs", "statefulsets", "serviceaccounts", "configmaps", "storageclasses", "horizontalpodautoscalers", "replicationcontrollers", "customresourcedefinitions"]
    {{else}}
    resources: {{ .Values.clusterrole.rules.resources}}
    {{end}}
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]
  - nonResourceURLs: [ "/metrics" ]
    verbs: [ "*" ]
{{end}}