apiVersion: v1
kind: ConfigMap
metadata:
  name: node-start-script
  namespace: {{ .Values.namespace }}
data:
  entrypoint.sh: |-
    #!/usr/bin/env bash

    cat >/whatap_conf/whatap.node.conf <<EOL
    license={{ .Values.whatap.license }}
    whatap.server.host={{ .Values.whatap.host }}
    whatap.server.port={{ .Values.whatap.port }}
    imageignore=k8s.gcr.io/pause:3.1,docker.io/openshift/origin-pod:v3.11.0
    commandignore=/pause,/usr/bin/pod
    whatap.name=$NODE_NAME
    helper_embedded=false
    EOL

    heapsize=$(echo "0.45 $WHATP_MEM_LIMIT" | awk '{print int($1 * $2 / 1048576)}')
    JAVA_OPTS="-Xms${heapsize}m -Xmx${heapsize}m"
    JAVA_OPTS="$JAVA_OPTS -XX:+UseG1GC -XX:+UseStringDeduplication  -XX:+ExitOnOutOfMemoryError -XshowSettings:vm"
    JAVA_OPTS="$JAVA_OPTS -Dwhatap.home=/whatap_conf"

    java $JAVA_OPTS -jar /data/agent/node/whatap.kube.node-*.jar
