{{- if .Values.deploymentOpen.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: whatap-openmx-config
  {{ if not .Values.namespaceOverrideEnabled }}
  namespace: "whatap-monitoring"
  {{ else}}
  namespace: {{ .Release.Namespace }}
  {{ end }}
data:
  scrape_config.yaml: |-
    {{ toYaml .Values.deploymentOpen.config | nindent 4 }}
{{- end }}