{{- if .Values.deploymentOpen.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: whatap-openmx-config
  {{ if not .Values.namespaceOverrideEnabled }}
  namespace: "whatap-monitoring"
  {{ else}}
  namespace: {{ .Release.Namespace }}
  {{ end }}
data:
  scrape_config.yaml: |-
    global:
      scrape_interval: {{ .Values.deploymentOpen.config.global.scrape_interval | quote }}
    scrape_configs:
{{ toYaml .Values.deploymentOpen.config.scrape_configs | indent 4 }}
{{- end }}