apiVersion: v1
kind: ConfigMap
metadata:
  name: whatap-npm-configmap
  {{ if not .Values.namespaceOverrideEnabled }}
  namespace: "whatap-monitoring"
  {{ else}}
  namespace: {{ .Release.Namespace }}
  {{ end }}
data:
  entrypoint.sh: |-
    #!/bin/bash
    WHATAP_BASE=/usr/whatap/whatap-npmd
    export WHATAP_NPM_HOME=$WHATAP_BASE
    export WHATAP_CONFIG_HOME=/usr/whatap/whatap-npmd/
    export WHATAP_CONFIG=whatap.conf

    export KUBERNETES_SERVICE_HOST=$KUBERNETES_SERVICE_HOST
    export KUBERNETES_SERVICE_PORT=$KUBERNETES_SERVICE_PORT

    /usr/whatap/whatap-npmd/install.sh x41pl22ek7jhv-z43cebasdv4il7-z62p3l35fj5502 15.165.146.117

    if [[ -n "" && -n "" && -n "" ]] ;
    then
        whatap_conf_path=$WHATAP_CONFIG_HOME/$WHATAP_CONFIG
        echo "awsInfoEnable=1" |  tee -a $whatap_conf_path > /dev/null
        echo "awsAccessKey=" |  tee -a $whatap_conf_path > /dev/null
        echo "awsSecretKey="  |  tee -a $whatap_conf_path > /dev/null
        echo "awsRegions=" |  tee -a $whatap_conf_path > /dev/null
    fi

    /usr/whatap/whatap-npmd/whatap_npmd
