apiVersion: v1
kind: ConfigMap
metadata:
  name: master-start-script
  namespace: {{ .Values.namespace }}
data:
  entrypoint.sh: |-
    #!/usr/bin/env bash

    mkdir /whatap_conf/confbase -p
    if [ ! -f /whatap_conf/confbase/whatap_server.conf ]; then
    cat >/whatap_conf/confbase/whatap_server.conf <<EOL
    license={{ .Values.whatap.license }}
    whatap.server.host={{ .Values.whatap.host }}
    whatap.server.port={{ .Values.whatap.port }}
    EOL
    fi

    if [ ! -f /whatap_conf/whatap.master.conf ]; then
    cat >/whatap_conf/whatap.master.conf <<EOL
    master_agent_port={{ .Values.deployment.containers.masterAgent.port }}
    license={{ .Values.whatap.license }}
    whatap.server.host={{ .Values.whatap.host }}
    whatap.server.port={{ .Values.whatap.port }}
    confbase_backup_enabled=true
    EOL
    fi

    heapsize=$(echo "0.45 $WHATP_MEM_LIMIT" | awk '{print int($1 * $2 / 1048576)}')
    JAVA_OPTS="-Xms${heapsize}m -Xmx${heapsize}m"
    JAVA_OPTS="$JAVA_OPTS -XX:+UseG1GC -XX:+UseStringDeduplication  -XX:+ExitOnOutOfMemoryError -XshowSettings:vm"
    JAVA_OPTS="$JAVA_OPTS -Dwhatap.home=/whatap_conf"

    java $JAVA_OPTS -cp /data/agent/confbase/whatap.agent.confbase-1.0.0.jar:/data/agent/master/whatap.kube.master-1.0.1.jar whatap.agent.App
