{{- if .Values.deploymentOpen.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: whatap-openmx-config
  namespace: {{ .Release.Namespace }}
data:
  scrape_config.yaml: |-
    {{ toYaml .Values.deploymentOpen.config | nindent 4 }}
{{- end }}