apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.daemonSet.name }}
  {{ if not .Values.namespaceOverrideEnabled }}
  namespace: "whatap-monitoring"
  {{ else}}
  namespace: {{ .Release.Namespace }}
  {{ end }}
  labels:
    name: {{ .Values.daemonSet.label }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.daemonSet.label }}
  template:
    metadata:
      labels:
        name: {{ .Values.daemonSet.label }}
    spec:
      {{- if .Values.imagePullSecret.name }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
      {{- end }}
      tolerations:
      {{- if .Values.daemonSet.tolerations}}
      {{- toYaml .Values.daemonSet.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.daemonSet.initContainers.nodeDebugger.enabled }}
      affinity:
      {{- if .Values.daemonSet.affinity }}
      {{- toYaml .Values.daemonSet.affinity | nindent 8 }}
      {{- end }}
      initContainers:
        - name:  {{ .Values.daemonSet.initContainers.nodeDebugger.name }}
          image: {{ .Values.daemonSet.initContainers.nodeDebugger.image }}
          command: ['/data/agent/tools/whatap_debugger', 'run']
          volumeMounts:
            - name: rootfs
              mountPath: /rootfs
              readOnly: true
      {{- end}}
      serviceAccountName: whatap
      containers:
      {{- if .Values.addon.gpu.enabled }}
        - name: "dcgm-exporter"
          {{- if .Values.addon.gpu.image }}
          image: {{ .Values.addon.gpu.image }}
          {{- else }}
          image: "nvcr.io/nvidia/k8s/dcgm-exporter:4.1.1-4.0.4-ubuntu22.04"
          {{- end }}
          env:
            - name: "DCGM_EXPORTER_LISTEN"
              value: ":9400"
            - name: "DCGM_EXPORTER_KUBERNETES"
              value: "true"
            - name: "DCGM_EXPORTER_COLLECTORS"
              value: "/etc/dcgm-exporter/whatap-dcgm-exporter.csv"
          ports:
            - name: "metrics"
              containerPort: 9400
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            capabilities:
              add:
                - SYS_ADMIN
          volumeMounts:
            - name: "pod-gpu-resources"
              readOnly: true
              mountPath: "/var/lib/kubelet/pod-resources"
            - name: "whatap-dcgm-exporter-csv"
              readOnly: true
              mountPath: "/etc/dcgm-exporter/whatap-dcgm-exporter.csv"
              subPath: whatap-gpu.csv
        {{ end }}
        - name: {{ .Values.daemonSet.containers.nodeHelper.name }}
          image: {{ .Values.daemonSet.containers.nodeHelper.image }}
          resources:
            requests:
              memory: {{ .Values.daemonSet.containers.nodeHelper.requests.memory}}
              cpu: {{ .Values.daemonSet.containers.nodeHelper.requests.cpu}}
            limits:
              memory: {{ .Values.daemonSet.containers.nodeHelper.limits.memory}}
              cpu: {{ .Values.daemonSet.containers.nodeHelper.limits.cpu}}
          ports:
            - name: helperport
              containerPort: 6801
          command: ['/data/agent/node/cadvisor_helper', '-port','6801']
          env:
            {{- if .Values.daemonSet.containers.nodeHelper.envs.collect_nfs_disk_enabled }}
            - name: collect_nfs_disk_enabled
              value: {{.Values.daemonSet.containers.nodeHelper.envs.collect_nfs_disk_enabled | quote}}
            {{- end }}
            {{- if .Values.daemonSet.containers.nodeHelper.envs.collect_kube_node_process_metric_enabled }}
            - name: collect_kube_node_process_metric_enabled
              value: {{.Values.daemonSet.containers.nodeHelper.envs.collect_kube_node_process_metric_enabled | quote}}
            {{- end }}
            {{- if .Values.daemonSet.containers.nodeHelper.envs.collect_kube_node_process_metric_target_list }}
            - name: collect_kube_node_process_metric_target_list
              value: {{.Values.daemonSet.containers.nodeHelper.envs.collect_kube_node_process_metric_target_list | quote}}
            {{- end }}
            {{- if .Values.daemonSet.containers.nodeHelper.envs.debug }}
            - name: debug
              value: {{.Values.daemonSet.containers.nodeHelper.envs.debug | quote}}
            {{- end }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            {{- if eq .Values.containerRuntime "containerd" }}
            - name: containerddomainsocket
              mountPath: /run/containerd/containerd.sock
            {{- else if eq .Values.containerRuntime "docker" }}
            - name: dockerdomainsocket
              mountPath: /var/run/docker.sock
            {{- else if eq .Values.containerRuntime "crio" }}
            - name: criodomainsocket
              mountPath: /var/run/crio/crio.sock
            {{- end }}
            - name: rootfs
              mountPath: /rootfs
              readOnly: true
            - name: hostsys
              mountPath: /sys
              readOnly: true
            - name: hostdiskdevice
              mountPath: /dev/disk
              readOnly: true
        - name: {{ .Values.daemonSet.containers.nodeAgent.name }}
          image: {{ .Values.daemonSet.containers.nodeAgent.image }}
          resources:
            requests:
              memory: {{ .Values.daemonSet.containers.nodeAgent.requests.memory}}
              cpu: {{ .Values.daemonSet.containers.nodeAgent.requests.cpu}}
            limits:
              memory: {{ .Values.daemonSet.containers.nodeAgent.limits.memory}}
              cpu: {{ .Values.daemonSet.containers.nodeAgent.limits.cpu}}
          ports:
            - name: nodeport
              containerPort: 6600
          command: ['/bin/entrypoint.sh']
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: WHATAP_LICENSE
              value: {{ .Values.whatap.license | quote }}
            - name: WHATAP_HOST
              value: {{ .Values.whatap.host | quote }}
            - name: WHATAP_PORT
              value: {{ .Values.whatap.port | quote }}
            - name: HOST_PREFIX
              value: "/rootfs"
            {{- if .Values.addon.gpu.enabled}}
            - name: gpu_enabled
              value: "true"
            {{ end }}
            - name: WHATAP_MEM_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: whatap-node-agent
                  resource: limits.memory
            {{- if .Values.daemonSet.containers.nodeAgent.envs.log_parser_containerd_std_enabled }}
            - name: log_parser_containerd_std_enabled
              value: {{.Values.daemonSet.containers.nodeAgent.envs.log_parser_containerd_std_enabled | quote}}
            {{- end }}
            {{- if .Values.daemonSet.containers.nodeAgent.envs.collect_kube_node_process_metric_enabled }}
            - name: collect_kube_node_process_metric_enabled
              value: {{.Values.daemonSet.containers.nodeAgent.envs.collect_kube_node_process_metric_enabled | quote}}
            {{- end }}
            {{- if .Values.daemonSet.containers.nodeAgent.envs.debug }}
            - name: debug
              value: {{.Values.daemonSet.containers.nodeAgent.envs.debug | quote}}
            {{- end }}
            {{- if .Values.daemonSet.containers.nodeAgent.envs.count_interval }}
            - name: count_interval
              value: {{.Values.daemonSet.containers.nodeAgent.envs.count_interval | quote}}
            {{- end }}
            {{- if eq .Values.collect_apiserver_metric_by_leader true }}
            - name: collect_apiserver_metric_by_leader
              value: "true"
            {{- end }}
            {{- if .Values.logsink_enabled }}
            - name: logsink_enabled
              value: "true"
            {{- end }}
            {{- if .Values.log_filter_enabled }}
            - name: log_filter_enabled
              value: "true"
            {{- end }}
            {{- if .Values.log_filter_allow_list }}
            - name: log_filter_allow_list
              value: {{ .Values.log_filter_allow_list | quote }}
            {{ end }}
            {{- if .Values.log_filter_deny_list }}
            - name: log_filter_deny_list
              value: {{ .Values.log_filter_deny_list | quote }}
            {{- end }}
          volumeMounts:
            - name: rootfs
              mountPath: /rootfs
              readOnly: true
            - name: start-script-volume
              mountPath: /bin/entrypoint.sh
              readOnly: true
              subPath: entrypoint.sh
            - mountPath: /whatap_conf
              name: whatap-config-volume
      volumes:
        {{- if eq .Values.containerRuntime "containerd" }}
        - hostPath:
            path: /run/containerd/containerd.sock
          name: containerddomainsocket
                {{- else if eq .Values.containerRuntime "docker" }}
        - hostPath:
            path: /var/run/docker.sock
          name: dockerdomainsocket
                {{- else if eq .Values.containerRuntime "crio" }}
        - hostPath:
            path: /var/run/crio/crio.sock
          name: criodomainsocket
                {{- end }}
        - hostPath:
            path: /
          name: rootfs
        - hostPath:
            path: /sys
          name: hostsys
        - hostPath:
            path: /dev/disk
          name: hostdiskdevice
        - name: start-script-volume
          configMap:
            defaultMode: 0700
            name: node-start-script
        - name: whatap-config-volume
          emptyDir: {}
        {{- if .Values.addon.gpu.enabled}}
        - hostPath:
            path: "/var/lib/kubelet/pod-resources"
          name: "pod-gpu-resources"
        - configMap:
            name: "dcgm-exporter-csv"
          name: "whatap-dcgm-exporter-csv"
        {{ end }}