{{- if .Values.deploymentOpen.enabled }}
{{- if .Values.k8sOldVersion }}
apiVersion: extensions/v1beta1
{{- else }}
apiVersion: apps/v1
{{end}}
kind: Deployment
metadata:
  name: {{ .Values.deploymentOpen.name }}
  {{ if not .Values.namespaceOverrideEnabled }}
  namespace: "whatap-monitoring"
  {{ else}}
  namespace: {{ .Release.Namespace }}
  {{ end }}
spec:
  replicas: {{ .Values.deploymentOpen.replicas }}
  {{- if not .Values.k8sOldVersion }}
  selector:
    matchLabels:
      name: {{ .Values.deploymentOpen.label }}
  {{end}}
  template:
    metadata:
      labels:
        name: {{ .Values.deploymentOpen.label }}
    spec:

      {{- if .Values.imagePullSecret.name }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
      {{- end }}
      tolerations:
      {{- if .Values.deploymentOpen.tolerations}}
      {{- toYaml .Values.deploymentOpen.tolerations | nindent 8 }}
      {{- end }}
      serviceAccountName: whatap
      volumes:
        - name: start-script-volume
          configMap:
            defaultMode: 0700
            name: open-start-script
        - name: whatap-config-volume
          emptyDir: {}
      containers:
        - name: {{ .Values.deploymentOpen.containers.openAgent.name }}
          image: {{ .Values.deploymentOpen.containers.openAgent.image }}
          resources:
            requests:
              memory: {{ .Values.deploymentOpen.containers.openAgent.resources.requests.memory }}
              cpu: {{ .Values.deploymentOpen.containers.openAgent.resources.requests.cpu }}
            limits:
              memory: {{ .Values.deploymentOpen.containers.openAgent.resources.limits.memory }}
              cpu: {{ .Values.deploymentOpen.containers.openAgent.resources.limits.cpu }}
          ports:
            - containerPort: {{ .Values.deploymentOpen.containers.openAgent.port }}
          command: ["/bin/entrypoint.sh"]
          env:
            - name: WHATAP_HOME
              value: "/whatap_conf"
            - name: WHATAP_LICENSE
              value: {{ .Values.whatap.license | quote}}
            - name: WHATAP_HOST
              value: {{ .Values.whatap.host | quote }}
            - name: WHATAP_PORT
              value: {{ .Values.whatap.port | quote }}
            - name: WHATAP_MEM_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: {{ .Values.deploymentOpen.containers.openAgent.name }}
                  resource: limits.memory
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: start-script-volume
              mountPath: /bin/entrypoint.sh
              readOnly: true
              subPath: entrypoint.sh
            - name: whatap-config-volume
              mountPath: /whatap_conf
{{- end }}