{{- if .Values.k8sOldVersion }}
apiVersion: extensions/v1beta1
{{- else }}
apiVersion: apps/v1
{{end}}
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  {{ if not .Values.namespaceOverrideEnabled }}
  namespace: "whatap-monitoring"
  {{ else}}
  namespace: {{ .Release.Namespace }}
  {{ end }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  {{- if not .Values.k8sOldVersion }}
  selector:
    matchLabels:
      name: {{ .Values.deployment.label }}
  {{end}}
  template:
    metadata:
      labels:
        name: {{ .Values.deployment.label }}
    spec:
      {{- if .Values.imagePullSecret.name }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
      {{- end }}
      serviceAccountName: whatap
      volumes:
        {{- if and .Values.addon.etcd_monitoring.enabled .Values.addon.etcd_monitoring.etcd_ca_cert_path}}
        - name: etcd-ca-cert-path
          hostPath:
            path: {{ default "/etc/kubernetes/pki/etcd/ca.crt" .Values.addon.etcd_monitoring.etcd_ca_cert_path }}
        {{- end }}
        {{- if and .Values.addon.etcd_monitoring.enabled .Values.addon.etcd_monitoring.etcd_ca_cert_path}}
        - name: etcd-client-cert-path
          hostPath:
            path: {{ default "/etc/kubernetes/pki/etcd/server.crt" .Values.addon.etcd_monitoring.etcd_ca_cert_path }}
        {{- end }}
        {{- if and .Values.addon.etcd_monitoring.enabled .Values.addon.etcd_monitoring.etcd_client_key_path}}
        - name: etcd-client-key-path
          hostPath:
            path: {{ default "/etc/kubernetes/pki/etcd/server.key" .Values.addon.etcd_monitoring.etcd_client_key_path }}
        {{- end }}
        - name: start-script-volume
          configMap:
            defaultMode: 0700
            name: master-start-script
        - name: whatap-config-volume
          emptyDir: {}
      containers:
        {{- if eq .Values.deployment.containers.controlPlaneHelper.enabled true}}
        - name: {{ .Values.deployment.containers.controlPlaneHelper.name }}
          image: {{ .Values.deployment.containers.controlPlaneHelper.image }}
          resources:
            requests:
              memory: {{ .Values.deployment.containers.controlPlaneHelper.resources.requests.memory }}
              cpu: {{ .Values.deployment.containers.controlPlaneHelper.resources.requests.cpu }}
            limits:
              memory: {{ .Values.deployment.containers.controlPlaneHelper.resources.limits.memory }}
              cpu: {{ .Values.deployment.containers.controlPlaneHelper.resources.limits.cpu }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.deployment.containers.controlPlaneHelper.port }}
          command: [ "/data/agent/master/whatap_control_plane_helper" ]
          args: [ "-collect_control_plane_monitoring_enabled=true" ]
          {{- if .Values.addon.etcd_monitoring.enabled}}
          volumeMounts:
            - name: etcd-ca-cert-path
              mountPath: {{ default "/etc/kubernetes/pki/etcd/ca.crt" .Values.addon.etcd_monitoring.etcd_ca_cert_path }}
              readOnly: true
            - name: etcd-client-cert-path
              mountPath: {{ default "/etc/kubernetes/pki/etcd/server.crt" .Values.addon.etcd_monitoring.etcd_client_cert_path }}
              readOnly: true
            - name: etcd-client-key-path
              mountPath: {{ default "/etc/kubernetes/pki/etcd/server.key" .Values.addon.etcd_monitoring.etcd_client_key_path }}
              readOnly: true
          {{- end }}
          env:
            - name: kube_apiserver_monitoring_enabled
            {{- if eq .Values.addon.apiserver_monitoring.enabled false }}
              value: "false"
            {{- else }}
              value: "true"
            {{- end }}
            - name: kube_client_tls_verify
            {{- if eq .Values.addon.apiserver_monitoring.client_tls_verify false }}
              value: "false"
            {{- else }}
              value: "true"
            {{- end }}
            - name: debug
            {{- if .Values.deployment.containers.controlPlaneHelper.debug }}
              value: "true"
            {{- else }}
              value: "false"
            {{- end }}
            - name: etcd_monitoring_enabled
            {{- if .Values.addon.etcd_monitoring.enabled }}
              value: "true"
            {{- else }}
              value: "false"
            {{- end }}
            {{- if and .Values.addon.etcd_monitoring.enabled .Values.addon.etcd_monitoring.etcd_ca_cert_path }}
            - name: etcd_ca_cert_path
              value: {{ .Values.addon.etcd_monitoring.etcd_ca_cert_path }}
            {{- end }}
            {{- if and .Values.addon.etcd_monitoring.enabled .Values.addon.etcd_monitoring.etcd_client_cert_path }}
            - name: etcd_client_cert_path
              value: {{ .Values.addon.etcd_monitoring.etcd_client_cert_path }}
            {{- end }}
            {{- if and .Values.addon.etcd_monitoring.enabled .Values.addon.etcd_monitoring.etcd_client_key_path }}
            - name: etcd_client_key_path
              value: {{ .Values.addon.etcd_monitoring.etcd_client_key_path }}
            {{- end }}
        {{- end }}
        - name: {{ .Values.deployment.containers.masterAgent.name }}
          image: {{ .Values.deployment.containers.masterAgent.image }}
          resources:
            requests:
              memory: {{ .Values.deployment.containers.masterAgent.resources.requests.memory }}
              cpu: {{ .Values.deployment.containers.masterAgent.resources.requests.cpu }}
            limits:
              memory: {{ .Values.deployment.containers.masterAgent.resources.limits.memory }}
              cpu: {{ .Values.deployment.containers.masterAgent.resources.limits.cpu }}
          ports:
            - containerPort: {{ .Values.deployment.containers.masterAgent.port }}
          command: ["/bin/entrypoint.sh"]
          env:
            {{- if eq .Values.collect_custom_resources true}}
            - name: collect_custom_resources
              value: "true"
            {{ end }}
            {{- if eq .Values.collect_custom_resources true}}
            - name: collect_cr
              value: "true"
            {{ end }}
            {{- if .Values.collect_custom_resources_interval}}
            - name: collect_cr_interval
              value: {{.Values.collect_custom_resources_interval | quote}}
            {{ end }}
            {{- if .Values.deployment.containers.controlPlaneHelper.enabled }}
            - name: collect_control_plane_monitoring_enabled
              value: "true"
            {{- end }}
            {{- if .Values.deployment.containers.masterAgent.envs.debug }}
            - name: debug
              value: "true"
            {{- end }}
            {{- if eq .Values.collect_apiserver_metric_by_leader true }}
            - name: collect_apiserver_metric_by_leader
              value: "true"
            {{- end }}
            - name: WHATAP_LICENSE
              value: {{ .Values.whatap.license | quote}}
            - name: WHATAP_HOST
              value: {{ .Values.whatap.host | quote }}
            - name: WHATAP_PORT
              value: {{ .Values.whatap.port | quote }}
            - name: WHATP_MEM_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: {{ .Values.deployment.containers.masterAgent.name }}
                  resource: limits.memory
          volumeMounts:
            - name: start-script-volume
              mountPath: /bin/entrypoint.sh
              readOnly: true
              subPath: entrypoint.sh
            - name: whatap-config-volume
              mountPath: /whatap_conf
            {{- if and .Values.addon.etcd_monitoring.enabled}}
            - name: etcd-ca-cert-path
              mountPath: {{ default "/etc/kubernetes/pki/etcd/ca.crt" .Values.addon.etcd_monitoring.etcd_ca_cert_path }}
              readOnly: true
            - name: etcd-client-cert-path
              mountPath: {{ default "/etc/kubernetes/pki/etcd/server.crt" .Values.addon.etcd_monitoring.etcd_client_cert_path }}
              readOnly: true
            - name: etcd-client-key-path
              mountPath: {{ default "/etc/kubernetes/pki/etcd/server.key" .Values.addon.etcd_monitoring.etcd_client_key_path }}
              readOnly: true
            {{- end }}