{{ if not .Values.namespaceOverrideEnabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: "whatap-monitoring"
  {{- if eq .Values.istioEnabled true }}
  labels:
    istio-injection: enabled
  {{end}}
{{end}}