apiVersion: v1
kind: Service
metadata:
  {{ if not .Values.namespaceOverrideEnabled }}
  namespace: "whatap-monitoring"
  {{ else}}
  namespace: {{ .Release.Namespace }}
  {{ end }}
  labels:
    run: whatap-master-agent
  name: whatap-master-agent
spec:
  clusterIP: None
  ports:
    - port: 6600
      protocol: TCP
      name: tcp-whatap-master-agent
    - port: 6800
      protocol: TCP
      name: tcp-whatap-confbase
  selector:
    name: whatap-master-agent
