# values.yaml
allowUse: false

whatap:
  license: # <license-key>
  host: # <whatap-server-host>
  port: # <whatap-server-port>
imagePullSecret:
  name:
# k8sOldVersion default
#k8sOldVersion: true
namespaceOverrideEnabled: false
deploymentOpen:
  enabled: true
  name: whatap-open-agent
  label: whatap-open-agent
  replicas: 1
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
  affinity: {}
  containers:
    openAgent:
      name: whatap-open-agent
      image: "whatap/kube_mon"
      port: 6600
      resources:
        requests:
          memory: "300Mi"
          cpu: "100m"
        limits:
          memory: "350Mi"
          cpu: "200m"
      envs:
        debug: false
  config:
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: ""
        static_config:
          targets:
            - ""
          filter:
            enabled: false